//! On-demand diagnostics. Browser traffic is generated by the chosen browser,
//! never by Tauri's WebView. No result can trigger application termination.
use crate::config::Config;
use serde::Serialize;
use std::{
    io::{Read, Write},
    net::{IpAddr, TcpListener, TcpStream, UdpSocket},
    sync::{
        atomic::{AtomicU64, Ordering},
        Arc, Mutex,
    },
    time::{Duration, Instant},
};

#[derive(Default)]
pub struct BrowserTests {
    latest: Arc<Mutex<Option<serde_json::Value>>>,
    generation: Arc<AtomicU64>,
}
#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct UdpReport {
    pub state: &'static str,
    pub text: String,
    pub scope: &'static str,
    pub attempts: Vec<serde_json::Value>,
    pub proxy_udp: serde_json::Value,
}
fn random<const N: usize>() -> Result<[u8; N], String> {
    let mut bytes = [0; N];
    std::fs::File::open("/dev/urandom")
        .and_then(|mut f| f.read_exact(&mut bytes))
        .map_err(|_| "无法创建安全测试会话".to_string())?;
    Ok(bytes)
}

// RFC 8489 Binding Success Response; validate transaction, cookie, declared
// length, attribute boundaries and family before interpreting XOR-MAPPED-ADDRESS.
fn mapped_address(packet: &[u8], transaction: &[u8; 12]) -> Option<IpAddr> {
    if packet.len() < 20
        || packet[..2] != [1, 1]
        || packet[4..8] != [0x21, 0x12, 0xa4, 0x42]
        || packet[8..20] != *transaction
    {
        return None;
    }
    let length = u16::from_be_bytes([packet[2], packet[3]]) as usize;
    if !length.is_multiple_of(4) || length + 20 != packet.len() {
        return None;
    }
    let mut offset = 20;
    while offset + 4 <= packet.len() {
        let kind = u16::from_be_bytes([packet[offset], packet[offset + 1]]);
        let len = u16::from_be_bytes([packet[offset + 2], packet[offset + 3]]) as usize;
        let value = packet.get(offset + 4..offset + 4 + len)?;
        if kind == 0x0020 {
            let cookie = [0x21, 0x12, 0xa4, 0x42];
            if value.len() == 8 && value[0] == 0 && value[1] == 1 {
                return Some(IpAddr::V4(std::net::Ipv4Addr::new(
                    value[4] ^ cookie[0],
                    value[5] ^ cookie[1],
                    value[6] ^ cookie[2],
                    value[7] ^ cookie[3],
                )));
            }
            if value.len() == 20 && value[0] == 0 && value[1] == 2 {
                let mut bytes = [0; 16];
                for i in 0..16 {
                    bytes[i] = value[i + 4] ^ if i < 4 { cookie[i] } else { transaction[i - 4] };
                }
                return Some(IpAddr::V6(std::net::Ipv6Addr::from(bytes)));
            }
        }
        offset += 4 + len.div_ceil(4) * 4;
    }
    None
}

// Resolve STUN independently through the saved proxy: a synthetic Fake-IP
// is unsuitable when a TUN cannot recover UDP domain metadata. Real addresses
// still use the ordinary OS UDP route; this does not bypass TUN routing.
fn stun_addresses(cfg: &Config, host: &str, port: u16) -> Vec<std::net::SocketAddr> {
    if !matches!(cfg.proxy_host.as_str(), "127.0.0.1" | "localhost" | "::1") || cfg.proxy_port == 0
    {
        return Vec::new();
    }
    let proxy_host = if cfg.proxy_host == "::1" {
        "[::1]"
    } else {
        &cfg.proxy_host
    };
    let Ok(proxy) = ureq::Proxy::new(format!("http://{proxy_host}:{}", cfg.proxy_port)) else {
        return Vec::new();
    };
    let agent = ureq::AgentBuilder::new()
        .try_proxy_from_env(false)
        .proxy(proxy)
        .redirects(0)
        .timeout(Duration::from_secs(4))
        .build();
    let mut addresses = Vec::new();
    // IPv4 supplies a real-address control even when system DNS returns Fake-IP.
    if let Ok(response) = agent
        .get(&format!(
            "https://cloudflare-dns.com/dns-query?name={host}&type=A"
        ))
        .set("accept", "application/dns-json")
        .call()
    {
        let mut body = String::new();
        if response
            .into_reader()
            .take(16385)
            .read_to_string(&mut body)
            .is_ok()
            && body.len() <= 16384
        {
            if let Ok(data) = serde_json::from_str::<serde_json::Value>(&body) {
                if let Some(answers) = data.get("Answer").and_then(|v| v.as_array()) {
                    for answer in answers {
                        if answer.get("type").and_then(|v| v.as_u64()) != Some(1) {
                            continue;
                        }
                        if let Some(ip) = answer
                            .get("data")
                            .and_then(|v| v.as_str())
                            .and_then(|v| v.parse::<std::net::Ipv4Addr>().ok())
                        {
                            if !ip.is_loopback()
                                && !ip.is_private()
                                && !ip.is_unspecified()
                                && !ip.is_multicast()
                                && !(ip.octets()[0] == 198 && matches!(ip.octets()[1], 18 | 19))
                            {
                                addresses.push(std::net::SocketAddr::new(IpAddr::V4(ip), port));
                            }
                        }
                    }
                }
            }
        }
    }
    addresses
}

fn probe_proxy_udp(cfg: &Config) -> serde_json::Value {
    let host = if cfg.proxy_host == "localhost" {
        "127.0.0.1"
    } else {
        &cfg.proxy_host
    };
    let Some(ip) = host.parse::<IpAddr>().ok().filter(IpAddr::is_loopback) else {
        return serde_json::json!({"state":"unknown","text":"仅允许已保存的本机代理入口"});
    };
    let proxy = std::net::SocketAddr::new(ip, cfg.proxy_port);
    let mut attempts = Vec::new();
    let mut seen = Vec::new();
    for (host, port) in [("stun.l.google.com", 19302), ("stun.cloudflare.com", 3478)] {
        let Ok(tx) = random::<12>() else {
            continue;
        };
        let mut query = vec![0, 1, 0, 0, 0x21, 0x12, 0xa4, 0x42];
        query.extend(tx);
        let result = crate::socks_udp::exchange(proxy, host, port, &query).and_then(|body| {
            mapped_address(&body, &tx).ok_or_else(|| "STUN 未返回有效出口地址".into())
        });
        match result {
            Ok(ip) => {
                seen.push(ip);
                attempts.push(serde_json::json!({"server":host,"state":"observed","egress":ip.to_string(),"text":"经本机 SOCKS 收到有效 STUN 回包"}));
            }
            Err(error) => {
                attempts.push(serde_json::json!({"server":host,"state":"unknown","text":error}))
            }
        }
    }
    let state = if seen.is_empty() || cfg.allowed_ips.is_empty() {
        "unknown"
    } else if seen
        .iter()
        .any(|ip| !crate::checks::ip_allowed(cfg, &ip.to_string()))
    {
        "risk"
    } else {
        "not_observed"
    };
    serde_json::json!({"state":state,"attempts":attempts,"text":if seen.is_empty(){"代理 UDP 未取得回包"}else if state=="risk"{"代理 UDP 出口不符合白名单"}else if state=="unknown"{"已取得代理 UDP 回包，尚未配置允许出口"}else{"代理 UDP 往返已验证，出口命中白名单"},"scope":"仅验证 ClaudeGuard 显式 SOCKS UDP 路径；不代表浏览器或 Claude 自动使用此路径"})
}

pub fn probe_udp(cfg: &Config) -> UdpReport {
    use std::net::ToSocketAddrs;
    let mut seen = std::collections::BTreeSet::new();
    let mut attempts = Vec::new();
    // DNS here deliberately uses the OS resolver, like a native application's
    // ordinary lookup. This is a self-probe, not observation of another app.
    for server in ["stun.cloudflare.com:3478", "stun.l.google.com:19302"] {
        let (send, receive) = std::sync::mpsc::channel();
        std::thread::spawn(move || {
            let result = server.to_socket_addrs().map(|a| a.collect::<Vec<_>>());
            let _ = send.send(result);
        });
        let system_addresses = receive
            .recv_timeout(Duration::from_secs(3))
            .ok()
            .and_then(Result::ok)
            .unwrap_or_default();
        let (host, port) = server.rsplit_once(':').unwrap();
        let mut addresses = stun_addresses(cfg, host, port.parse().unwrap());
        let source = if addresses.is_empty() {
            "系统解析"
        } else {
            "经现有代理取得真实 IPv4；UDP 仍使用系统路由"
        };
        addresses.extend(system_addresses);
        if addresses.is_empty() {
            attempts.push(serde_json::json!({"server":server,"stage":"resolve","result":"系统解析与独立真实地址查询均失败"}));
            continue;
        }
        for v6 in [false, true] {
            let Some(address) = addresses.iter().find(|a| a.is_ipv6() == v6) else {
                continue;
            };
            let mut detail = serde_json::json!({"server":server,"family":if v6 {"IPv6"} else {"IPv4"},"destination":address.to_string(),"resolution":if v6 {"系统解析"}else{source},"result":"未收到有效 STUN 应答"});
            let Ok(socket) = UdpSocket::bind(if v6 { "[::]:0" } else { "0.0.0.0:0" }) else {
                continue;
            };
            let _ = socket.set_read_timeout(Some(Duration::from_secs(2)));
            let _ = socket.set_write_timeout(Some(Duration::from_secs(2)));
            let Ok(tx) = random::<12>() else {
                continue;
            };
            let mut query = vec![0, 1, 0, 0, 0x21, 0x12, 0xa4, 0x42];
            query.extend(tx);
            if let Err(error) = socket.connect(address).and_then(|_| socket.send(&query)) {
                detail["result"] = serde_json::json!(format!("发送失败：{:?}", error.kind()));
                attempts.push(detail);
                continue;
            }
            let mut bytes = [0; 2048];
            if let Ok(n) = socket.recv(&mut bytes) {
                if let Some(ip) = mapped_address(&bytes[..n], &tx) {
                    detail["result"] = serde_json::json!("收到有效 STUN 应答");
                    detail["egress"] = serde_json::json!(ip.to_string());
                    seen.insert(ip);
                }
            }
            attempts.push(detail);
        }
    }
    let unexpected = seen
        .iter()
        .filter(|ip| !crate::checks::ip_allowed(cfg, &ip.to_string()))
        .count();
    let (state, text) = if seen.is_empty() {
        (
            "unknown",
            "未收到有效 STUN 应答；可能被阻止、服务不可达或不支持 UDP，不能据此判定安全".into(),
        )
    } else if cfg.allowed_ips.is_empty() {
        (
            "unknown",
            format!("观察到 {} 个 UDP 出口；尚未配置允许的出口", seen.len()),
        )
    } else if unexpected > 0 {
        (
            "risk",
            format!("观察到 {unexpected} 个白名单之外的 UDP 出口；需结合实际应用和代理路径核验"),
        )
    } else {
        (
            "not_observed",
            "本次 STUN 出口均命中白名单；不代表其他应用或其他目标的流量".into(),
        )
    };
    let proxy_udp = probe_proxy_udp(cfg);
    UdpReport {
        state,
        text,
        scope: "ClaudeGuard 自身 · 系统路由 · 非目标 App 抓包",
        attempts,
        proxy_udp,
    }
}

pub fn probe_system_dns(cfg: &Config) -> serde_json::Value {
    use std::net::ToSocketAddrs;
    let scope = "macOS 系统解析器采样（ClaudeGuard 发起，不代表应用内置 DoH）";
    let run = || -> Result<serde_json::Value, String> {
        let id = api(cfg, "id")?;
        let id = id.trim();
        if id.is_empty()
            || id.len() > 63
            || !id.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'-')
        {
            return Err("DNS 测试会话无效".into());
        }
        let (send, recv) = std::sync::mpsc::channel();
        for i in 1..=6 {
            let name = format!("{i}.{id}.bash.ws:443");
            let send = send.clone();
            std::thread::spawn(move || {
                let resolved = name.to_socket_addrs().is_ok();
                // A Fake-IP lookup alone may never reach an authoritative DNS
                // server. Exercise a real native HTTPS connection through OS
                // routing (including an existing TUN), without an HTTP proxy.
                // Any HTTP response suffices; no response body is consumed.
                let requested = ureq::AgentBuilder::new()
                    .try_proxy_from_env(false)
                    .redirects(0)
                    .timeout(Duration::from_secs(4))
                    .build()
                    .get(&format!(
                        "https://{}/probe.png",
                        name.trim_end_matches(":443")
                    ))
                    .call();
                let connected = matches!(requested, Ok(_) | Err(ureq::Error::Status(_, _)));
                let _ = send.send((resolved, connected));
            });
        }
        drop(send);
        let deadline = Instant::now() + Duration::from_secs(6);
        let mut resolved_count = 0;
        let mut connected_count = 0;
        for _ in 0..6 {
            match recv.recv_timeout(deadline.saturating_duration_since(Instant::now())) {
                Ok((resolved, connected)) => {
                    resolved_count += usize::from(resolved);
                    connected_count += usize::from(connected);
                }
                Err(_) => break,
            }
        }
        std::thread::sleep(Duration::from_secs(2));
        let data: serde_json::Value =
            serde_json::from_str(&api(cfg, &format!("dnsleak/test/{id}?json"))?)
                .map_err(|_| "DNS 结果格式无效")?;
        let records = match dns_records(&data) {
            Ok(records) => records,
            Err(error) => {
                return Ok(
                    serde_json::json!({"state":"unknown","scope":scope,"resolvers":[],"resolvedRequests":resolved_count,"connectedRequests":connected_count,"text":error}),
                )
            }
        };
        let resolvers: Vec<_> = records.iter().filter(|v| v.get("type").and_then(|v|v.as_str()) == Some("dns")).take(32).map(|v| {
            let field=|key|v.get(key).and_then(|v|v.as_str()).unwrap_or("").chars().take(100).collect::<String>();
            serde_json::json!({"ip":field("ip"),"country":field("country_name"),"asn":field("asn")})
        }).collect();
        Ok(
            serde_json::json!({"state":if resolvers.is_empty(){"unknown"}else{"observed"},"scope":scope,"resolvers":resolvers,"resolvedRequests":resolved_count,"connectedRequests":connected_count,"text":"解析器 IP 与代理出口不同不自动判定泄露；需要结合预期 DNS 策略及实际路径"}),
        )
    };
    run().unwrap_or_else(|error| serde_json::json!({"state":"unknown","scope":scope,"text":error}))
}

fn dns_records(data: &serde_json::Value) -> Result<&Vec<serde_json::Value>, &'static str> {
    if let Some(records) = data.as_array() {
        return Ok(records);
    }
    if data
        .get("error")
        .and_then(serde_json::Value::as_str)
        .is_some_and(|error| error.contains("No DNS servers found"))
    {
        return Err(
            "检测服务未观察到公网解析器；Fake-IP、缓存或服务状态均可能影响采样，不能判定安全",
        );
    }
    Err("DNS 检测服务未返回有效解析器列表")
}

fn api(cfg: &Config, suffix: &str) -> Result<String, String> {
    let host = if cfg.proxy_host == "::1" {
        "[::1]"
    } else {
        &cfg.proxy_host
    };
    let proxy = ureq::Proxy::new(format!("http://{host}:{}", cfg.proxy_port))
        .map_err(|_| "代理入口无效")?;
    let response = ureq::AgentBuilder::new()
        .proxy(proxy)
        .timeout(Duration::from_secs(6))
        .redirects(0)
        .build()
        .get(&format!("https://bash.ws/{suffix}"))
        .call();
    let response = match response {
        Ok(response) => response,
        Err(error) => {
            // Some endpoints reject this TLS client while macOS curl succeeds.
            // Retry through the SAME explicit proxy with normal TLS validation;
            // never retry directly or ignore certificates.
            return api_with_system_tls(cfg, suffix).map_err(|_| match error {
                ureq::Error::Status(code, _) => {
                    format!("DNS 检测后端未完成请求（HTTP {code}；系统客户端重试也失败）")
                }
                ureq::Error::Transport(error) => format!(
                    "DNS 检测后端未完成请求（{:?}；系统客户端重试也失败）",
                    error.kind()
                ),
            });
        }
    };
    let mut text = String::new();
    response
        .into_reader()
        .take(32769)
        .read_to_string(&mut text)
        .map_err(|_| "DNS 后端响应无效")?;
    if text.len() > 32768 {
        return Err("DNS 后端响应过大".into());
    }
    Ok(text)
}

fn api_with_system_tls(cfg: &Config, suffix: &str) -> Result<String, String> {
    use std::{
        fs::OpenOptions,
        os::unix::fs::OpenOptionsExt,
        process::{Command, Stdio},
    };
    struct PrivateOutput(std::path::PathBuf);
    impl Drop for PrivateOutput {
        fn drop(&mut self) {
            let _ = std::fs::remove_file(&self.0);
        }
    }
    let nonce = random::<24>()?
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect::<String>();
    let output = PrivateOutput(std::env::temp_dir().join(format!("cg-dns-{nonce}")));
    OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .open(&output.0)
        .map_err(|_| "无法创建临时 DNS 结果")?;
    let host = if cfg.proxy_host == "::1" {
        "[::1]"
    } else {
        &cfg.proxy_host
    };
    let mut child = Command::new("/usr/bin/curl")
        .args([
            "--silent",
            "--fail",
            "--proto",
            "=https",
            "--max-time",
            "10",
            "--connect-timeout",
            "5",
            "--max-filesize",
            "32768",
            "--noproxy",
            "",
            "--proxy",
        ])
        .arg(format!("http://{host}:{}", cfg.proxy_port))
        .arg("--output")
        .arg(&output.0)
        .arg(format!("https://bash.ws/{suffix}"))
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
        .map_err(|_| "系统 DNS 客户端不可用")?;
    let deadline = Instant::now() + Duration::from_secs(12);
    loop {
        match child.try_wait() {
            Ok(Some(status)) if status.success() => break,
            Ok(None) if Instant::now() < deadline => std::thread::sleep(Duration::from_millis(50)),
            _ => {
                let _ = child.kill();
                let _ = child.wait();
                return Err("系统 DNS 客户端请求失败".into());
            }
        }
    }
    let mut text = String::new();
    std::fs::File::open(&output.0)
        .and_then(|file| file.take(32769).read_to_string(&mut text))
        .map_err(|_| "DNS 后端响应无效")?;
    if text.len() > 32768 {
        return Err("DNS 后端响应过大".into());
    }
    Ok(text)
}
fn respond(stream: &mut TcpStream, status: &str, mime: &str, data: &str) {
    let response = format!("HTTP/1.1 {status}\r\nContent-Type: {mime}\r\nContent-Length: {}\r\nCache-Control: no-store\r\nX-Content-Type-Options: nosniff\r\nReferrer-Policy: no-referrer\r\nConnection: close\r\n\r\n{data}",data.len());
    let _ = stream.write_all(response.as_bytes());
    let _ = stream.shutdown(std::net::Shutdown::Write);
}
impl BrowserTests {
    pub fn invalidate(&self) {
        self.generation.fetch_add(1, Ordering::SeqCst);
        *self.latest.lock().unwrap() = None;
    }
    pub fn report(&self) -> Option<serde_json::Value> {
        self.latest.lock().unwrap().clone()
    }
    pub fn start(&self, cfg: Config) -> Result<String, String> {
        let generation = self.generation.clone();
        let epoch = generation.fetch_add(1, Ordering::SeqCst) + 1;
        let listener = TcpListener::bind("127.0.0.1:0").map_err(|_| "无法启动浏览器测试")?;
        listener
            .set_nonblocking(true)
            .map_err(|_| "无法启动浏览器测试")?;
        let host = listener
            .local_addr()
            .map_err(|_| "无法读取测试端口")?
            .to_string();
        let token: String = random::<24>()?.iter().map(|b| format!("{b:02x}")).collect();
        let path = format!("/{token}");
        let url = format!("http://{host}{path}/");
        let mut settings = serde_json::to_string(&cfg.allowed_ips).unwrap();
        // Values originate in config; avoid script termination even if a legacy
        // config was manually edited and has not passed form validation.
        settings = settings
            .replace('<', "\\u003c")
            .replace('>', "\\u003e")
            .replace('&', "\\u0026");
        let html =
            include_str!("../ui-mac/browser-test.html").replace("__ALLOWED_IPS__", &settings);
        let latest = self.latest.clone();
        *latest.lock().unwrap() = None;

        std::thread::spawn(move || {
            let deadline = Instant::now() + Duration::from_secs(600);
            let mut dns_id: Option<String> = None;
            let mut dns_requested = false;
            let mut stun_requested = false;
            while Instant::now() < deadline && generation.load(Ordering::SeqCst) == epoch {
                let (mut stream, _) = match listener.accept() {
                    Ok(pair) => pair,
                    Err(_) => {
                        std::thread::sleep(Duration::from_millis(50));
                        continue;
                    }
                };
                let _ = stream.set_read_timeout(Some(Duration::from_secs(2)));
                let _ = stream.set_write_timeout(Some(Duration::from_secs(2)));
                let request_deadline = Instant::now() + Duration::from_secs(3);
                let mut raw = Vec::new();
                let mut byte = [0; 1];
                while raw.len() < 8192
                    && !raw.ends_with(b"\r\n\r\n")
                    && Instant::now() < request_deadline
                {
                    if stream.read_exact(&mut byte).is_err() {
                        break;
                    }
                    raw.push(byte[0]);
                }
                if !raw.ends_with(b"\r\n\r\n") {
                    continue;
                }
                let Ok(header) = std::str::from_utf8(&raw) else {
                    continue;
                };
                let first: Vec<_> = header
                    .lines()
                    .next()
                    .unwrap_or("")
                    .split_whitespace()
                    .collect();
                if first.len() != 3 {
                    continue;
                }
                let headers: Vec<_> = header
                    .lines()
                    .skip(1)
                    .filter_map(|s| s.split_once(':'))
                    .collect();
                let field = |name: &str| {
                    headers
                        .iter()
                        .find(|(k, _)| k.eq_ignore_ascii_case(name))
                        .map(|(_, v)| v.trim())
                };
                if field("Host") != Some(host.as_str())
                    || field("Origin").is_some_and(|o| o != format!("http://{host}"))
                {
                    respond(&mut stream, "403 Forbidden", "text/plain", "Forbidden");
                    continue;
                }
                let Some(route) = first[1].strip_prefix(&path) else {
                    respond(&mut stream, "404 Not Found", "text/plain", "Not found");
                    continue;
                };
                match (first[0], route) {
                    ("GET", "/") => {
                        respond(&mut stream, "200 OK", "text/html; charset=utf-8", &html)
                    }
                    ("POST", "/dns-start") if !dns_requested => {
                        dns_requested = true;
                        let result = api(&cfg, "id").and_then(|s| {
                            let id = s.trim();
                            if id.is_empty()
                                || id.len() > 64
                                || !id.bytes().all(|b| b.is_ascii_alphanumeric() || b == b'-')
                            {
                                return Err("DNS 会话无效".into());
                            }
                            dns_id = Some(id.to_owned());
                            Ok(serde_json::json!({"id":id}).to_string())
                        });
                        let body =
                            result.unwrap_or_else(|e| serde_json::json!({"error":e}).to_string());
                        respond(&mut stream, "200 OK", "application/json", &body);
                    }
                    ("POST", "/stun-config") if !stun_requested => {
                        stun_requested = true;
                        let mut urls = Vec::new();
                        for (host, port) in
                            [("stun.cloudflare.com", 3478), ("stun.l.google.com", 19302)]
                        {
                            let addresses = stun_addresses(&cfg, host, port);
                            if let Some(address) = addresses.first() {
                                urls.push(format!("stun:{address}"));
                            } else {
                                urls.push(format!("stun:{host}:{port}"));
                            }
                        }
                        respond(
                            &mut stream,
                            "200 OK",
                            "application/json",
                            &serde_json::json!({"urls":urls}).to_string(),
                        );
                    }
                    ("POST", "/dns-result") => {
                        let result = dns_id
                            .take()
                            .ok_or_else(|| "DNS 会话尚未创建或已读取".into())
                            .and_then(|id| api(&cfg, &format!("dnsleak/test/{id}?json")));
                        let body = result
                            .unwrap_or_else(|e: String| serde_json::json!({"error":e}).to_string());
                        respond(&mut stream, "200 OK", "application/json", &body);
                    }
                    ("POST", "/report") => {
                        let n = field("Content-Length")
                            .and_then(|s| s.parse::<usize>().ok())
                            .unwrap_or(0);
                        if n == 0 || n > 16384 || field("Transfer-Encoding").is_some() {
                            continue;
                        }
                        let mut body = vec![0; n];
                        let mut received = 0;
                        while received < n && Instant::now() < request_deadline {
                            match stream.read(&mut body[received..]) {
                                Ok(0) | Err(_) => break,
                                Ok(count) => received += count,
                            }
                        }
                        if received == n && Instant::now() < request_deadline {
                            if let Ok(value) = serde_json::from_slice::<serde_json::Value>(&body) {
                                if generation.load(Ordering::SeqCst) == epoch {
                                    *latest.lock().unwrap() = Some(value);
                                }
                                respond(&mut stream, "200 OK", "application/json", "{}");
                            }
                        }
                    }
                    _ => respond(&mut stream, "404 Not Found", "text/plain", "Not found"),
                }
            }
        });
        Ok(url)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_service_sampling_is_unknown_instead_of_a_leak_or_success() {
        assert!(
            dns_records(&serde_json::json!({"error":"No DNS servers found. Try again..."}))
                .unwrap_err()
                .contains("不能判定安全")
        );
        assert!(dns_records(&serde_json::json!([{"type":"dns"}])).is_ok());
        assert!(dns_records(&serde_json::json!({"unexpected":true})).is_err());
    }

    #[test]
    fn system_tls_retry_uses_the_explicit_proxy_and_returns_failure_on_refusal() {
        let listener = TcpListener::bind("127.0.0.1:0").unwrap();
        let port = listener.local_addr().unwrap().port();
        listener.set_nonblocking(true).unwrap();
        let server = std::thread::spawn(move || {
            let deadline = Instant::now() + Duration::from_secs(3);
            loop {
                if let Ok((mut stream, _)) = listener.accept() {
                    stream
                        .set_read_timeout(Some(Duration::from_secs(2)))
                        .unwrap();
                    let mut request = Vec::new();
                    let mut byte = [0];
                    while request.len() < 4096 && !request.ends_with(b"\r\n\r\n") {
                        if stream.read_exact(&mut byte).is_err() {
                            break;
                        }
                        request.push(byte[0]);
                    }
                    let _ = stream.write_all(b"HTTP/1.1 502 Bad Gateway\r\nContent-Length: 0\r\nConnection: close\r\n\r\n");
                    return String::from_utf8(request).unwrap();
                }
                assert!(
                    Instant::now() < deadline,
                    "System TLS client did not use the selected proxy"
                );
                std::thread::sleep(Duration::from_millis(10));
            }
        });
        let cfg = Config {
            proxy_port: port,
            ..Config::default()
        };
        assert!(api_with_system_tls(&cfg, "id").is_err());
        assert!(server
            .join()
            .unwrap()
            .starts_with("CONNECT bash.ws:443 HTTP/1.1\r\n"));
    }
    fn http(
        url: &str,
        suffix: &str,
        host_override: Option<&str>,
        origin: Option<&str>,
        body: Option<&str>,
    ) -> String {
        let rest = url.strip_prefix("http://").unwrap();
        let (host, path) = rest.split_once('/').unwrap();
        let mut socket = TcpStream::connect(host).unwrap();
        socket
            .set_read_timeout(Some(Duration::from_secs(3)))
            .unwrap();
        let target = format!("/{}{}", path.trim_end_matches('/'), suffix);
        let body = body.unwrap_or("");
        let origin = origin
            .map(|s| format!("Origin: {s}\r\n"))
            .unwrap_or_default();
        write!(
            socket,
            "{} {target} HTTP/1.1\r\nHost: {}\r\n{origin}Content-Length: {}\r\n\r\n{body}",
            if suffix == "/report" { "POST" } else { "GET" },
            host_override.unwrap_or(host),
            body.len()
        )
        .unwrap();
        let mut result = String::new();
        if let Err(error) = socket.read_to_string(&mut result) {
            assert!(
                error.kind() == std::io::ErrorKind::ConnectionReset && !result.is_empty(),
                "{error}"
            );
        }
        result
    }
    #[test]
    fn browser_server_rejects_cross_origin_and_dns_rebinding() {
        let tests = BrowserTests::default();
        let url = tests.start(Config::default()).unwrap();
        assert!(http(&url, "/", Some("attacker.example"), None, None).starts_with("HTTP/1.1 403"));
        assert!(http(
            &url,
            "/report",
            None,
            Some("https://attacker.example"),
            Some("{} ")
        )
        .starts_with("HTTP/1.1 403"));
        assert!(tests.report().is_none());
        assert!(http(&url, "/", None, None, None).contains("当前浏览器"));
        assert!(http(&url, "/../../config.json", None, None, None).starts_with("HTTP/1.1 404"));
        tests.invalidate();
    }
    #[test]
    fn browser_reports_are_memory_only_and_configuration_change_invalidates_them() {
        let tests = BrowserTests::default();
        let url = tests.start(Config::default()).unwrap();
        assert!(
            http(&url, "/report", None, None, Some(r#"{"scope":"browser"}"#))
                .starts_with("HTTP/1.1 200")
        );
        assert!(tests.report().is_some());
        tests.invalidate();
        assert!(tests.report().is_none());
        let next = tests.start(Config::default()).unwrap();
        assert_ne!(url, next);
        tests.invalidate();
    }
    #[test]
    fn stun_rejects_wrong_transaction_and_truncation() {
        let tx = [7; 12];
        let mut p = vec![1, 1, 0, 12, 0x21, 0x12, 0xa4, 0x42];
        p.extend(tx);
        p.extend([
            0,
            0x20,
            0,
            8,
            0,
            1,
            0,
            0,
            203 ^ 0x21,
            0 ^ 0x12,
            113 ^ 0xa4,
            4 ^ 0x42,
        ]);
        assert_eq!(
            mapped_address(&p, &tx),
            Some("203.0.113.4".parse().unwrap())
        );
        assert!(mapped_address(&p, &[8; 12]).is_none());
        for n in 0..p.len() {
            assert!(mapped_address(&p[..n], &tx).is_none());
        }
        p[23] = 30;
        assert!(mapped_address(&p, &tx).is_none());
    }
    #[test]
    fn stun_ipv6_and_family_are_checked() {
        let tx = [9; 12];
        let ip: std::net::Ipv6Addr = "2001:db8::5".parse().unwrap();
        let mut p = vec![1, 1, 0, 24, 0x21, 0x12, 0xa4, 0x42];
        p.extend(tx);
        p.extend([0, 0x20, 0, 20, 0, 2, 0, 0]);
        let mask = [0x21, 0x12, 0xa4, 0x42, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9, 9];
        p.extend(ip.octets().iter().zip(mask).map(|(a, b)| a ^ b));
        assert_eq!(mapped_address(&p, &tx), Some(IpAddr::V6(ip)));
        p[25] = 3;
        assert!(mapped_address(&p, &tx).is_none());
    }
}
